### ISSUE TITLE
TODO Applications

### ISSUE THREAD

**Issue by aputron** [aputron/streamlitapps#1]
- [x] FACS visualization

- [x] Primer Generation: Ligase/Gibson

- [x] Barcode Primer Generation

- [x] _In-silico_ Mutant Library Generation

- [x] Mutant library variation visualization
